name: Test Action with Email Step

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f1000751@ds.study.iitm.ac.in
        run: echo "Hello, world!"
